# Generated by Django 5.2.17 on 2026-09-22 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import common.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=2)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BranchMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branch_memberships",
                        to="members.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["organization", "status"], name="branches_br_organiz_c6f32d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="branches_branch_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="branch_tenant_code"
            ),
        ),
        migrations.AddIndex(
            model_name="branchmembership",
            index=models.Index(
                fields=["organization", "member"], name="branches_br_organiz_efb12e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branchmembership",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"),
                name="branches_branchmembership_tenant_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="branchmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("branch", "member"),
                name="branch_active_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="branchmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("left_at__isnull", True)),
                fields=("organization", "member"),
                name="member_one_primary_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="branchmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_primary", False), ("left_at__isnull", True), _connector="OR"
                ),
                name="primary_branch_is_current",
            ),
        ),
    ]
