# Generated by Django 5.2.17 on 2026-09-22 12:34

import django.utils.timezone
from django.db import migrations, models

import common.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField(default=common.ids.new_id, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("event_version", models.PositiveSmallIntegerField(default=1)),
                ("aggregate_type", models.CharField(max_length=80)),
                ("aggregate_id", models.UUIDField()),
                ("organization_id", models.UUIDField(null=True)),
                ("correlation_id", models.CharField(max_length=128)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_at", models.DateTimeField(null=True)),
                ("last_error", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="outbox_outb_status_ab1c80_idx",
                    ),
                    models.Index(
                        fields=["status", "available_at"],
                        name="outbox_outb_status_ed6984_idx",
                    ),
                ],
            },
        ),
    ]
