# Generated by Django 5.2.17 on 2026-09-22 12:34

import django.db.models.deletion
from django.db import migrations, models

import common.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_user_id", models.UUIDField(null=True)),
                ("action", models.CharField(max_length=100)),
                ("resource_type", models.CharField(max_length=80)),
                ("resource_id", models.UUIDField()),
                ("metadata", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("correlation_id", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="audit_audit_organiz_01c53f_idx",
                    ),
                    models.Index(
                        fields=["actor_member", "created_at"],
                        name="audit_audit_actor_m_b18a4e_idx",
                    ),
                ],
            },
        ),
    ]
