# Generated by Django 5.2.17 on 2026-09-22 12:34

import django.db.models.deletion
from django.db import migrations, models

import common.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("BUSINESS", "Business"),
                            ("NONPROFIT", "Nonprofit"),
                            ("OTHER", "Other"),
                        ],
                        default="BUSINESS",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DISABLED", "Disabled"),
                            ("DELETED", "Deleted"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("logo_media_id", models.UUIDField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("country_code", models.CharField(default="IN", max_length=2)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allow_member_invites", models.BooleanField(default=True)),
                ("allow_group_creation", models.BooleanField(default=True)),
                ("allow_external_chat", models.BooleanField(default=False)),
                ("max_members", models.PositiveIntegerField(blank=True, null=True)),
                ("max_teams", models.PositiveIntegerField(blank=True, null=True)),
                ("default_timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="organizations_organizationsettings_tenant_id",
                    )
                ],
            },
        ),
    ]
