# Generated by Django 5.2.17 on 2026-09-22 12:34

import django.db.models.deletion
from django.db import migrations, models

import common.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "employee_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("LEFT", "Left"),
                            ("REMOVED", "Removed"),
                        ],
                        default="INVITED",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="members_mem_organiz_122411_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="members_member_tenant_id"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user_id__isnull", False)),
                        fields=("organization", "user_id"),
                        name="member_tenant_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("employee_code__isnull", False)),
                        fields=("organization", "employee_code"),
                        name="member_tenant_employee",
                    ),
                ],
            },
        ),
    ]
