# Generated by Django 5.2.17 on 2026-09-22 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import common.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("members", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("DEPARTMENT", "Department"),
                            ("PROJECT", "Project"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MEMBER", "Member"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("LEFT", "Left")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_memberships",
                        to="members.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="teams.team"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["organization", "branch"], name="teams_team_organiz_242f5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["organization", "status"], name="teams_team_organiz_19f1fe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="teams_team_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="team_tenant_name"
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["organization", "member"], name="teams_teamm_organiz_84dfbb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="teams_teammembership_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("team", "member"),
                name="team_active_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("left_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("left_at__isnull", False), ("status", "LEFT")),
                    _connector="OR",
                ),
                name="team_membership_dates",
            ),
        ),
    ]
