import { Activity, Building2, MessageSquare, Users } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";
import { activities, health, members, operationalMetrics, primaryMetrics } from "@/features/dashboard/data/demo-dashboard";

const icons = [Building2, Users, MessageSquare, Activity];

export default function DashboardPage() {
  return <main className="mx-auto max-w-7xl p-4 sm:p-6"><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-slate-500">Overview</p><h1 className="text-2xl font-semibold">Dashboard</h1><p className="text-sm text-slate-500">Overview of your GlobalChat workspace and platform activity.</p></div><button className="rounded-md border bg-white px-3 py-2 text-sm">Refresh</button></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{primaryMetrics.map((metric,index)=>{const Icon=icons[index];return <article className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm" key={metric.label}><Icon size={19} className="text-indigo-600"/><p className="mt-4 text-sm text-slate-500">{metric.label}</p><strong className="text-2xl">{metric.value}</strong><p className="mt-1 text-xs text-emerald-700">{metric.change}</p></article>})}</section><section className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{operationalMetrics.map(metric=><div className="rounded-lg border bg-white p-3" key={metric.label}><p className="text-xs text-slate-500">{metric.label}</p><b>{metric.value}</b><p className="text-xs text-slate-400">{metric.change}</p></div>)}</section><section className="mt-4 grid gap-4 xl:grid-cols-2"><article className="rounded-lg border bg-white p-5"><h2 className="font-semibold">Recent Activity</h2>{activities.map((activity,index)=><p className="border-b py-3 text-sm last:border-0" key={activity}>{activity}<span className="float-right text-xs text-slate-400">{index + 1}h</span></p>)}</article><article className="overflow-x-auto rounded-lg border bg-white p-5"><h2 className="mb-3 font-semibold">Recent Members</h2><table className="min-w-[580px] w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Member</th><th>Organization</th><th>Role</th><th>Status</th><th>Joined</th></tr></thead><tbody>{members.map(member=><tr className="border-t" key={member.email}><td className="py-3"><b>{member.name}</b><small className="block text-slate-500">{member.email}</small></td><td>{member.organization}</td><td>{member.role}</td><td><StatusBadge status={member.status}/></td><td>{member.joined}</td></tr>)}</tbody></table></article></section><article className="mt-4 rounded-lg border bg-white p-5"><h2 className="font-semibold">System Health</h2><div className="mt-3 grid gap-x-8 md:grid-cols-2">{health.map(service=><p className="flex justify-between border-b py-2 text-sm" key={service.name}>{service.name}<span className="flex gap-2"><StatusBadge status={service.status}/><span className="text-slate-400">{service.latency}</span></span></p>)}</div></article></main>;
}
